DynamicsLink/Models/Invoice.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Threading.Tasks;

namespace DynamicsLink.Models
{
    public class Invoice
    {
        public int ID { get; set; }
        public int ItemID { get; set; }
        [ForeignKey("ItemID")]
        public Item Item { get; set; }
        public int UnitID { get; set; }
        [ForeignKey("UnitID")]
        public Unit Unit { get; set; }
        public int Price { get; set; }
        public int Qty { get; set; }
        public int Total { get; set; }
        public int Discount { get; set; }
        public int Net { get; set; }
        public int InoviceContainerNo { get; set; }
        [AllowNull]
        public int? InvoicesContainerID { get; set; }
        [ForeignKey("InvoicesContainerID")]
        public InvoiceContainer InvoiceContainer { get; set; }
    }
}

DynamicsLink/Controllers/InvoicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DynamicsLink.Data;
using DynamicsLink.Models;

namespace DynamicsLink.Controllers
{
    public class InvoicesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public InvoicesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Invoices
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Invoices.Include(i => i.Item).Include(i => i.Unit);
            return View(await applicationDbContext.ToListAsync());
        }
        public  IActionResult NewInvoice()
        {
            ViewData["ItemID"] = new SelectList(_context.Items, "ID", "Name");
            ViewData["UnitID"] = new SelectList(_context.Units, "ID", "Name");
            ViewData["StoreID"] = new SelectList(_context.Stores, "ID", "Name");
            var InvoiceID = _context.InvoicesContainer.OrderByDescending(u => u.No).FirstOrDefault();
            ViewBag.InvoiceID = InvoiceID.No+1;
            return View();
        }
        public ICollection<Item> StoreChanged(int? id)
        {
            return _context.Items.Where(i=>i.StoreID==id).ToList();
        }
        public ICollection<Unit> ItemChanged(int? id)
        {
            return _context.Units.Where(i => i.ItemID == id).ToList();
        }

        // GET: Invoices/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var invoice = await _context.Invoices
                .Include(i => i.Item)
                .Include(i => i.Unit)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (invoice == null)
            {
                return NotFound();
            }

            return View(invoice);
        }

        // GET: Invoices/Create
        public IActionResult Create()
        {
            ViewData["ItemID"] = new SelectList(_context.Items, "ID", "Name");
            ViewData["UnitID"] = new SelectList(_context.Units, "ID", "Name");
            return View();
        }

        // POST: Invoices/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create( Invoice invoice)
        {
            if (ModelState.IsValid)
            {
                _context.Invoices.Add(invoice);
                 _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ItemID"] = new SelectList(_context.Items, "ID", "Name", invoice.ItemID);
            ViewData["UnitID"] = new SelectList(_context.Units, "ID", "Name", invoice.UnitID);
            return View(invoice);
        }
        [HttpPost]
        public IActionResult CreateContainer(InvoiceContainer invoiceContainer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(invoiceContainer);
                _context.SaveChanges();
                var id = _context.InvoicesContainer.FirstOrDefault(c => c.No == invoiceContainer.No).ID;
                var invoices = _context.Invoices.Where(i => i.InoviceContainerNo == invoiceContainer.No).ToList();
                foreach (var item in invoices)
                {
                    item.InvoicesContainerID = id;
                }
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        // GET: Invoices/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var invoice = await _context.Invoices.FindAsync(id);
            if (invoice == null)
            {
                return NotFound();
            }
            ViewData["ItemID"] = new SelectList(_context.Items, "ID", "ID", invoice.ItemID);
            ViewData["UnitID"] = new SelectList(_context.Units, "ID", "ID", invoice.UnitID);
            return View(invoice);
        }

        // POST: Invoices/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,ItemID,UnitID,Price,Qty,Total,Discount,Net")] Invoice invoice)
        {
            if (id != invoice.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(invoice);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InvoiceExists(invoice.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ItemID"] = new SelectList(_context.Items, "ID", "ID", invoice.ItemID);
            ViewData["UnitID"] = new SelectList(_context.Units, "ID", "ID", invoice.UnitID);
            return View(invoice);
        }

        // GET: Invoices/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var invoice = await _context.Invoices
                .Include(i => i.Item)
                .Include(i => i.Unit)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (invoice == null)
            {
                return NotFound();
            }

            return View(invoice);
        }

        // POST: Invoices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var invoice = await _context.Invoices.FindAsync(id);
            _context.Invoices.Remove(invoice);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InvoiceExists(int id)
        {
            return _context.Invoices.Any(e => e.ID == id);
        }
    }
}

DynamicsLink/Views/Invoices/Create.cshtml
@model DynamicsLink.Models.Invoice

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Invoice</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ItemID" class="control-label"></label>
                <select asp-for="ItemID" class ="form-control" asp-items="ViewBag.ItemID"></select>
            </div>
            <div class="form-group">
                <label asp-for="UnitID" class="control-label"></label>
                <select asp-for="UnitID" class ="form-control" asp-items="ViewBag.UnitID"></select>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Qty" class="control-label"></label>
                <input asp-for="Qty" class="form-control" />
                <span asp-validation-for="Qty" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Total" class="control-label"></label>
                <input asp-for="Total" class="form-control" />
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Discount" class="control-label"></label>
                <input asp-for="Discount" class="form-control" />
                <span asp-validation-for="Discount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Net" class="control-label"></label>
                <input asp-for="Net" class="form-control" />
                <span asp-validation-for="Net" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

DynamicsLink/Views/Invoices/Delete.cshtml
@model DynamicsLink.Models.Invoice

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Invoice</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Item)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Item.ID)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Unit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Unit.ID)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Qty)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Qty)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Total)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Discount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Discount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Net)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Net)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DynamicsLink/Views/Invoices/Details.cshtml
@model DynamicsLink.Models.Invoice

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Invoice</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Item)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Item.ID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Unit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Unit.ID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Qty)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Qty)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Total)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Discount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Discount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Net)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Net)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DynamicsLink/Views/Invoices/Edit.cshtml
@model DynamicsLink.Models.Invoice

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Invoice</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="ItemID" class="control-label"></label>
                <select asp-for="ItemID" class="form-control" asp-items="ViewBag.ItemID"></select>
                <span asp-validation-for="ItemID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UnitID" class="control-label"></label>
                <select asp-for="UnitID" class="form-control" asp-items="ViewBag.UnitID"></select>
                <span asp-validation-for="UnitID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Qty" class="control-label"></label>
                <input asp-for="Qty" class="form-control" />
                <span asp-validation-for="Qty" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Total" class="control-label"></label>
                <input asp-for="Total" class="form-control" />
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Discount" class="control-label"></label>
                <input asp-for="Discount" class="form-control" />
                <span asp-validation-for="Discount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Net" class="control-label"></label>
                <input asp-for="Net" class="form-control" />
                <span asp-validation-for="Net" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

DynamicsLink/Views/Invoices/Index.cshtml
@model IEnumerable<DynamicsLink.Models.Invoice>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Item)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Unit)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Qty)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Total)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Discount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Net)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Unit.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Qty)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Total)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Discount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Net)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

DynamicsLink/Views/Invoices/NewInvoice.cshtml
@model DynamicsLink.Models.Invoice
@{
    ViewData["Title"] = "NewInvoice";
}
<br />
<div class="row container">
    <div class="col-sm-6">Inovice No:<span id="InvoiceID">@ViewBag.InvoiceID</span></div>
    <div class="col-sm-6">Inovice Date @DateTime.Today</div>
</div>
<br />
<div class="row container">
    <div class="form-group col-sm-6">
        <label class="control-label">Store</label>
        <select id="state-target" asp-items="ViewBag.StoreID">
            <option selected></option>
        </select>
    </div>
</div>
<div asp-validation-summary="ModelOnly" class="text-danger"></div>

<form>
    
    <div class="row">
        <div class="col-sm-10">
            <table id="myTable" class="table">
                <tbody>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Item)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Unit)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Price)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Qty)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Total)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Discount)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Net)
                        </th>
                        <th></th>
                    </tr>

                    <tr>
                        <td>
                            <div class="form-group">
                                <label asp-for="Item" class="control-label"></label>
                                <select style="width:auto" id="items" asp-for="ItemID" class="form-control"></select>
                            </div>
                        </td>
                        <td>
                            <div class="form-group">
                                <label asp-for="Unit" class="control-label"></label>
                                <select style="width:auto" id="units" asp-for="UnitID" class="form-control"></select>
                            </div>
                        </td>
                        <td>
                            <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input id="Price" asp-for="Price" disabled class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                        </td>
                        <td>
                            <div class="form-group">
                                <label asp-for="Qty" class="control-label"></label>
                                <input id="Qty" asp-for="Qty" class="form-control" />
                                <span asp-validation-for="Qty" class="text-danger"></span>
                            </div>
                        </td>
                        <td>
                            <div class="form-group">
                                <label asp-for="Total" class="control-label"></label>
                                <input id="Total" asp-for="Total" disabled class="form-control" />
                                <span asp-validation-for="Total" class="text-danger"></span>
                            </div>
                        </td>
                        <td>
                            <div class="form-group">
                                <label asp-for="Discount" class="control-label"></label>%
                                <input id="Discount" asp-for="Discount" disabled value="5" class="form-control" />
                                <span asp-validation-for="Discount" class="text-danger"></span>
                            </div>
                        </td>
                        <td>
                            <div class="form-group">
                                <label asp-for="Net" class="control-label"></label>
                                <input id="Net" asp-for="Net" disabled class="form-control" />
                                <span asp-validation-for="Net" class="text-danger"></span>
                            </div>
                        </td>
                        <td>
                            <label class="control-label">Add</label>
                            <div class="form-group">
                                <button id="add" type="button" value="Add" class="btn btn-primary">Add</button>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-sm-2">

        </div>
    </div>
</form>
@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "__AjaxAntiForgeryForm" }))
{
    @Html.AntiForgeryToken()
}
<div class="row">
    <div class="col-sm-6"></div>
    <div class="col-sm-6">
        <div>
        <h4>Total:<span id="TotalAll"></span></h4>
        </div>
        <div>
        <h4 id="TaxesAll">Taxes:14%</h4>
        </div>
        <div>
        <h4 >Net:<span id="NetAll"></span></h4>
        </div>
    </div>
</div>
<a id="saveAll" class="btn btn-primary">Save</a>
@section Scripts
{
    <script>
        var invoice = [];
        var prices = [];
        var TotalAll= 0;
        var TaxesAll= 14;
        var NetAll= 0;
        $(document).ready(function () {
            $("#state-target").on("change", function () {
                $list = $("#items");
                $.ajax({
                    url:"@Url.Action("StoreChanged", "Invoices")",
                    type: "GET",
                    data: { id: $("#state-target").val() }, //id of the state which is used to extract cities
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function (result) {
                        console.log(result);
                        $list.empty();
                        $list.append('<option slected></option>');
                        $.each(result, function (i, item) {
                            $list.append('<option value="' + item["id"] + '"> ' + item["name"] + ' </option>');
                            var price = { id: item["id"], price: item["price"] };
                            prices[item["id"]] = item["price"];
                        });

                    },
                    error: function (request, error) {
                        alert("Request: " + JSON.stringify(request));
                    }
                });
            });

            $("#items").on("change", function () {
                $('#Price').val(prices[$('#items').val()]);
                $list = $("#units");
                $.ajax({
                    url:"@Url.Action("ItemChanged", "Invoices")",
                    type: "GET",
                    data: { id: $("#items").val() }, //id of the state which is used to extract cities
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function (result) {

                        $list.empty();
                        $list.append('<option slected></option>');
                        $.each(result, function (i, item) {
                            $list.append('<option value="' + item["id"] + '"> ' + item["name"] + ' </option>');
                        });

                    },
                    error: function (request, error) {
                        alert("Request: " + JSON.stringify(request));
                    }
                });
            });
            $('#Qty').on("change", function () {
                $('#Total').val($('#Price').val() * $('#Qty').val());
                $('#Net').val($('#Total').val() - $('#Total').val() / $('#Discount').val());
            });

            $('#add').on("click", function () {
                $('#myTable tr:last').before('<tr><td>' + $('#items option:selected').html() + '</td><td>'
                + $('#units option:selected').html() + '</td><td>' + $('#Price').val() + '</td><td>'
                + $('#Qty').val() + '</td><td>' + $('#Total').val()
                    + '</td><td>' + $('#Discount').val() + '</td><td>' + $('#Net').val() + '</td></tr>');
                var form = $('#__AjaxAntiForgeryForm');
                var token = $('input[name="__RequestVerificationToken"]', form).val();

                var data = {
                    __RequestVerificationToken: token,
                    itemID: $("#items").val(),
                    UnitID: $("#units").val(),
                    price: $('#Price').val(),
                    qty: $('#Qty').val(),
                    Total: $('#Total').val(),
                    Discount: $('#Discount').val(),
                    Net: $('#Net').val(),
                    InvoicesContainerID: $('#InvoiceID').html()
                };

                invoice.push(data)
                console.log(invoice);
                TotalAll = TotalAll + parseInt($('#Total').val());
                $('#TotalAll').html(TotalAll);
                $('#NetAll').html(Math.round(TotalAll - TotalAll / TaxesAll));
            $.ajax({
                url: '/Invoices/Create',
                type: 'POST',
                data: {
                    __RequestVerificationToken: token,
                    itemID: $("#items").val(),
                    UnitID: $("#units").val(),
                    price: $('#Price').val(),
                    qty: $('#Qty').val(),
                    Total: $('#Total').val(),
                    Discount: $('#Discount').val(),
                    Net: $('#Net').val(),
                    InoviceContainerNo: $('#InvoiceID').html()
                    },
                success: function (data) {
                    alert(data.success);
                },
                error: function () {
                    alert("error");
                }
                });
            });
            jQuery.ajaxSettings.traditional = true;
            $('#saveAll').on("click", function () {
                var No = $('#InvoiceID').html();
                $.ajax({
                    url: '/Invoices/CreateContainer',
                    type: 'POST',
                    data: {
                        No: No,
                        Total: TotalAll,
                        Taxes: TaxesAll,
                        Net: NetAll
                            },
                        success: function (data) {
                            alert(data.success);
                        },
                        error: function () {
                            alert("error");
                        }
                    });
               
            });

        });
        @*function newInvoice() {

            $('#myTable tr:last').before('<tr><td>' + $('#items option:selected').html() + '</td><td>'
                + $('#units option:selected').html() + '</td><td>' + $('#Price').val() + '</td><td>'
                + $('#Qty').val() + '</td><td>' + $('#Total').val()
                + '</td><td>' + $('#Discount').val() + '</td><td>' + $('#Net').val() + '</td></tr>');

            $.ajax({
                    url: "@Url.Action("Create", "Invoices")",
                    method: "POST",
                    data: {
                    ItemID: $("#items").val(),
                    UnitID: $("#units").val(),
                    Price: $('#Price').val(),
                    Qty: $('#Qty').val(),
                    Total: $('#Total').val(),
                    Discount: $('#Discount').val(),
                    Net: $('#Net').val()
                      },
                    //contentType: "application/json; charset=utf-8",
                    //dataType: "json",
                    success: function (result) {
                    },
                error: function (request, error) {
                    console.log("Request: " + JSON.stringify(request));
                    }
                });
        };*@
    </script>
}